language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"

matrix:
  allow_failures:
    - python: "nightly"
    - python: "pypy"

branches:
  only:
    - master

install:
  # Travis has pypy 2.5.0, which is way too old, so we upgrade it on the fly:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="5.6.0"
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
  - travis_retry pip install pylint
  - travis_retry pip install -r app/requirements.txt
  - travis_retry pip install -r tests/requirements.txt
  - travis_retry pip install pytest-cov coverage coveralls codacy-coverage

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.pyenv

script:
  py.test --cov=app

after_success:
  - pylint --disable=fixme app
  - coveralls
  - coverage xml && python-codacy-coverage -r coverage.xml
